### ISSUE TITLE
An error occurs during installation, shipping-docker/vessel

### ISSUE THREAD

**Issue by batFormat** [shipping-docker/php-composer#3]
An error occurs during installation
```
docker run --rm \
    -v $(pwd):/opt \
    -w /opt \
    shippingdocker/php-composer:latest \
    composer require shipping-docker/vessel
```

![image](https://user-images.githubusercontent.com/13119245/66499414-75aad700-eac8-11e9-98fc-a979376aab68.png)

**Comment by fideloper** [comment]
Hi!

It's been a while since this was opened :D

The base image uses `php7.(2|3|4)-cli` which doesn't have all the extensions everyone may need for their projects. I'll try to update it to include some more soon.

**Comment by fideloper** [comment]
Should be updated when Docker Hub finishes their automatic builds (sorry, you probably don't care this many months later :D)
